MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = commdesc.txt Races.txt attack.txt \
general.txt objects.txt tang.txt defend.txt \
birth.txt Demigods.txt helpinfo.txt option.txt town.txt \
bldg.txt Personalities.txt version.txt Classes.txt \
dungeon.txt magic.txt editor.txt pref.txt \
command.txt faq.txt MonsterRaces.txt gambling.txt \
monster.txt

PACKAGE = help

